vigilia: Update the tests for the use of the YAML::PP perl module.
Ran these command, additional information inserted:

╰─$ ./bin/vigilia command-correct 000-display-builtin-workflows-help-page

---
error: 3:Child PID 3565096 exited with status 0
path:
  000_context_path: 10/_3/_1
  010_module_name: 40_workflow-automator/12_help-pages/summary.yml
  020_command_definition_path: command_definitions/110_default-builtin-workflows.yml
  030_description: Can we display the builtin workflows help page?
  040_subdescription: default builtin workflows
  050_executed_command: bin/workflow --help-workflows
  060_command_prefix: ''
report_error_directory: ./report_workflow-automation-engine/000-display-builtin-workflows-help-page
summary_filename: ./report_workflow-automation-engine/000-display-builtin-workflows-help-page/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/001-display-builtin-workflow-packages-with-summary-descriptions

---
error: 3:Child PID 3565112 exited with status 0
path:
  000_context_path: 10/_5/_1
  010_module_name: 40_workflow-automator/12_help-pages/summary.yml
  020_command_definition_path: command_definitions/130_default-builtin-convenience-modules.yml
  030_description: Can we display the builtin workflow packages with the summary descriptions?
  040_subdescription: default builtin packages
  050_executed_command: bin/workflow --help-builtin-packages-all
  060_command_prefix: ''
report_error_directory: ./report_workflow-automation-engine/001-display-builtin-workflow-packages-with-summary-descriptions
summary_filename: ./report_workflow-automation-engine/001-display-builtin-workflow-packages-with-summary-descriptions/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/002-help-Command--Net--IPerf-builtin-package

---
error: 3:Child PID 3565152 exited with status 0
path:
  000_context_path: 10/_11/_1
  010_module_name: 40_workflow-automator/12_help-pages/summary.yml
  020_command_definition_path: command_definitions/137_help-Command--Net--IPerf-builtin-convenience-module.yml
  030_description: help of the Command::Net::IPerf builtin package
  040_subdescription: help of the Command::Net::IPerf builtin package
  050_executed_command: bin/workflow Command::Net::IPerf --help-builtin-package
  060_command_prefix: ''
report_error_directory: ./report_workflow-automation-engine/002-help-Command--Net--IPerf-builtin-package
summary_filename: ./report_workflow-automation-engine/002-help-Command--Net--IPerf-builtin-package/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/003-Have-project-workflows-been-correctly-installed/

---
error: 3:Child PID 3569415 exited with status 0
path:
  000_context_path: 12/_13/_1
  010_module_name: 40_workflow-automator/25_smoke/summary.yml
  020_command_definition_path: command_definitions/340_correct-installation-workflows-new-project.yml
  030_description: Have the project workflows been correctly installed?
  040_subdescription: correct installation of the workflows of the new project
  050_executed_command: cd workflow-test && workflow-tests-workflow --help-workflows
  060_command_prefix: docker exec -it --user neurospaces workflow_automation_test_container bash -ic
report_error_directory: ./report_workflow-automation-engine/003-Have-project-workflows-been-correctly-installed
summary_filename: ./report_workflow-automation-engine/003-Have-project-workflows-been-correctly-installed/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/004-Have-project-workflows-been-correctly-installed,-different-working-directory/

---
error: 3:Child PID 3569456 exited with status 0
path:
  000_context_path: 12/_14/_1
  010_module_name: 40_workflow-automator/25_smoke/summary.yml
  020_command_definition_path: command_definitions/360_correct-installation-workflows-new-project,-different-working-directory.yml
  030_description: Have the project workflows been correctly installed, different working directory?
  040_subdescription: correct installation of the workflows of the new project, different working directory
  050_executed_command: workflow-tests-workflow --help-workflows
  060_command_prefix: docker exec -it --user neurospaces workflow_automation_test_container bash -ic
report_error_directory: ./report_workflow-automation-engine/004-Have-project-workflows-been-correctly-installed,-different-working-directory
summary_filename: ./report_workflow-automation-engine/004-Have-project-workflows-been-correctly-installed,-different-working-directory/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/005-list-known-workflow-projects-regular-workflow-executable/

---
error: 3:Child PID 3569673 exited with status 0
path:
  000_context_path: 12/_20/_1
  010_module_name: 40_workflow-automator/25_smoke/summary.yml
  020_command_definition_path: command_definitions/480_listing-known-workflow-projects-workflow-executable.yml
  030_description: Can we list the known workflow projects using the regular workflow executable?
  040_subdescription: listing the known workflow projects using the workflow executable
  050_executed_command: workflow --help-projects
  060_command_prefix: docker exec -it --user neurospaces workflow_automation_test_container bash -ic
report_error_directory: ./report_workflow-automation-engine/005-list-known-workflow-projects-regular-workflow-executable
summary_filename: ./report_workflow-automation-engine/005-list-known-workflow-projects-regular-workflow-executable/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/006-generate-archive-created-configuration/

---
error: 3:Child PID 3569713 exited with status 0
path:
  000_context_path: 12/_21/_1
  010_module_name: 40_workflow-automator/25_smoke/summary.yml
  020_command_definition_path: command_definitions/500_creation-archive-configuration.yml
  030_description: Can we generate an archive of the created configuration?
  040_subdescription: creation of an archive of a configuration
  050_executed_command: workflow-tests-workflow --verbose builtin configuration_archive /tmp/wtw.tar.gz
  060_command_prefix: docker exec -it --user neurospaces workflow_automation_test_container bash -ic
report_error_directory: ./report_workflow-automation-engine/006-generate-archive-created-configuration
summary_filename: ./report_workflow-automation-engine/006-generate-archive-created-configuration/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/007-find-workflow-project-cd-feature-tests/
./bin/vigilia: *** Error: './vigilia/specifications/40_workflow-automator/30_specific-features-cd.t/get_command_definition_path(): no command_definition_path' not found. at ./bin/vigilia line 1310.

<will likely need manual correction>

---
error: 3:Child PID 3575365 exited with status 0
path:
  000_context_path: 14/_2/_1
  010_module_name: 40_workflow-automator/30_specific-features-cd.t
  020_command_definition_path: 'get_command_definition_path(): no command_definition_path'
  030_description: Can we find the workflow project for the cd feature tests?
  040_subdescription: find the workflow project for the cd feature tests
  050_executed_command: workflow --help-projects
  060_command_prefix: docker exec -it --user neurospaces workflow_feature_testing_container bash -ic
report_error_directory: ./report_workflow-automation-engine/007-find-workflow-project-cd-feature-tests
summary_filename: ./report_workflow-automation-engine/007-find-workflow-project-cd-feature-tests/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/008-find-workflow-project-export-sh-feature-tests/

---
error: 3:Child PID 3580212 exited with status 0
path:
  000_context_path: 16/_2/_1
  010_module_name: 40_workflow-automator/32_specific-features-export-sh/summary.yml
  020_command_definition_path: command_definitions/110_find-workflow-project-export-sh-feature-tests.yml
  030_description: Can we find the workflow project for the export-sh feature tests?
  040_subdescription: find the workflow project for the export-sh feature tests
  050_executed_command: workflow --help-projects
  060_command_prefix: docker exec -it --user neurospaces workflow_feature_testing_container bash -ic
report_error_directory: ./report_workflow-automation-engine/008-find-workflow-project-export-sh-feature-tests
summary_filename: ./report_workflow-automation-engine/008-find-workflow-project-export-sh-feature-tests/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/009-abcd-project-configuration-directory/

---
error: 3:Child PID 3589975 exited with status 0
path:
  000_context_path: 20/_4/_1
  010_module_name: 40_workflow-automator/38_rename_project/summary.yml
  020_command_definition_path: command_definitions/130_abcd-project-known-command-filenames.yml
  030_description: abcd project configuration directory
  040_subdescription: abcd project workflow_filenames_known
  050_executed_command: abcd-workflow builtin workflow_filenames_known
  060_command_prefix: docker exec -it --user neurospaces workflow_project_rename bash -ic
report_error_directory: ./report_workflow-automation-engine/009-abcd-project-configuration-directory
summary_filename: ./report_workflow-automation-engine/009-abcd-project-configuration-directory/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/010-renamed-workflow-file-known-workflow-implementation-files/

---
error: 3:Child PID 3599448 exited with status 0
path:
  000_context_path: 24/_8/_1
  010_module_name: 40_workflow-automator/46_builtin/summary.yml
  020_command_definition_path: command_definitions/190_renamed-workflow-file-known-workflow-implementation-files.yml
  030_description: Do we see the renamed workflow file in the known workflow implementation files?
  040_subdescription: Do we see the renamed workflow file in the known workflow implementation files?
  050_executed_command: feature-testing-workflow builtin workflow_filenames_known
  060_command_prefix: docker exec -it --user neurospaces workflow_features_installed_container bash -ic
report_error_directory: ./report_workflow-automation-engine/010-renamed-workflow-file-known-workflow-implementation-files
summary_filename: ./report_workflow-automation-engine/010-renamed-workflow-file-known-workflow-implementation-files/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/011-Are-unimplemented-bash-completors-and-help-pagers-correctly-reported/

---
error: 3:Child PID 3599538 exited with status 0
path:
  000_context_path: 24/_10/_1
  010_module_name: 40_workflow-automator/46_builtin/summary.yml
  020_command_definition_path: command_definitions/205_Are-unimplemented-bash-completors-and-help-pagers-correctly-reported-before-workflow-removal.yml
  030_description: Are unimplemented bash completors and help pagers correctly reported?
  040_subdescription: Are unimplemented bash completors and help pagers correctly reported?
  050_executed_command: feature-testing-workflow builtin lint 'python|scripts'
  060_command_prefix: docker exec -it --user neurospaces workflow_features_installed_container bash -ic
report_error_directory: ./report_workflow-automation-engine/011-Are-unimplemented-bash-completors-and-help-pagers-correctly-reported
summary_filename: ./report_workflow-automation-engine/011-Are-unimplemented-bash-completors-and-help-pagers-correctly-reported/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/012-Has-workflow-implementation-file-been-removed/

---
error: 3:Child PID 3599641 exited with status 0
path:
  000_context_path: 24/_12/_1
  010_module_name: 40_workflow-automator/46_builtin/summary.yml
  020_command_definition_path: command_definitions/220_Has-workflow-implementation-file-been-removed.yml
  030_description: Has the workflow implementation file been removed?
  040_subdescription: Has the workflow implementation file been removed?
  050_executed_command: feature-testing-workflow builtin workflow_filenames_known
  060_command_prefix: docker exec -it --user neurospaces workflow_features_installed_container bash -ic
report_error_directory: ./report_workflow-automation-engine/012-Has-workflow-implementation-file-been-removed
summary_filename: ./report_workflow-automation-engine/012-Has-workflow-implementation-file-been-removed/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/013-Are-unimplemented-bash-completors-and-help-pagers-correctly-reported-after-have/

---
error: 3:Child PID 3599686 exited with status 0
path:
  000_context_path: 24/_13/_1
  010_module_name: 40_workflow-automator/46_builtin/summary.yml
  020_command_definition_path: command_definitions/230_Are-unimplemented-bash-completors-and-help-pagers-correctly-reported.yml
  030_description: Are unimplemented bash completors and help pagers correctly reported after we have removed the workflow implementation file?
  040_subdescription: Are unimplemented bash completors and help pagers correctly reported after we have removed the workflow implementation file?
  050_executed_command: feature-testing-workflow builtin lint 'python|scripts'
  060_command_prefix: docker exec -it --user neurospaces workflow_features_installed_container bash -ic
report_error_directory: ./report_workflow-automation-engine/013-Are-unimplemented-bash-completors-and-help-pagers-correctly-reported-after-have
summary_filename: ./report_workflow-automation-engine/013-Are-unimplemented-bash-completors-and-help-pagers-correctly-reported-after-have/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/014-find-correct-commands-feature-testing-workflows/

---
error: 3:Child PID 3605152 exited with status 0
path:
  000_context_path: 26/_2/_1
  010_module_name: 40_workflow-automator/80_install-testing/10_debian/summary.yml
  020_command_definition_path: command_definitions/200_find-correct-commands-feature-testing-workflows.yml
  030_description: Do we find the correct commands for the feature-testing workflows?
  040_subdescription: Do we find the correct commands for the feature-testing workflows?
  050_executed_command: feature-testing-workflow --help-workflows
  060_command_prefix: docker exec -it --user neurospaces workflow_install_testing_debian_container bash -ic
report_error_directory: ./report_workflow-automation-engine/014-find-correct-commands-feature-testing-workflows
summary_filename: ./report_workflow-automation-engine/014-find-correct-commands-feature-testing-workflows/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/015-find-correct-commands-feature-testing-workflows/

---
error: 3:Child PID 3607392 exited with status 0
path:
  000_context_path: 27/_2/_1
  010_module_name: 40_workflow-automator/80_install-testing/20_ubuntu/summary.yml
  020_command_definition_path: command_definitions/200_find-correct-commands-feature-testing-workflows.yml
  030_description: Do we find the correct commands for the feature-testing workflows?
  040_subdescription: Do we find the correct commands for the feature-testing workflows?
  050_executed_command: feature-testing-workflow --help-workflows
  060_command_prefix: docker exec -it --user neurospaces workflow_install_testing_ubuntu_container bash -ic
report_error_directory: ./report_workflow-automation-engine/015-find-correct-commands-feature-testing-workflows
summary_filename: ./report_workflow-automation-engine/015-find-correct-commands-feature-testing-workflows/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/016-find-correct-commands-feature-testing-workflows/

---
error: 3:Child PID 3609588 exited with status 0
path:
  000_context_path: 28/_2/_1
  010_module_name: 40_workflow-automator/80_install-testing/30_fedora/summary.yml
  020_command_definition_path: command_definitions/200_find-correct-commands-feature-testing-workflows.yml
  030_description: Do we find the correct commands for the feature-testing workflows?
  040_subdescription: Do we find the correct commands for the feature-testing workflows?
  050_executed_command: feature-testing-workflow --help-workflows
  060_command_prefix: docker exec -it --user neurospaces workflow_install_testing_fedora_container bash -ic
report_error_directory: ./report_workflow-automation-engine/016-find-correct-commands-feature-testing-workflows
summary_filename: ./report_workflow-automation-engine/016-find-correct-commands-feature-testing-workflows/000_summary.yml

╰─$ ./bin/vigilia command-correct report_workflow-automation-engine/017-find-correct-commands-feature-testing-workflows/

---
error: 3:Child PID 3611631 exited with status 0
path:
  000_context_path: 29/_2/_1
  010_module_name: 40_workflow-automator/80_install-testing/40_opensuse/summary.yml
  020_command_definition_path: command_definitions/200_find-correct-commands-feature-testing-workflows.yml
  030_description: Do we find the correct commands for the feature-testing workflows?
  040_subdescription: Do we find the correct commands for the feature-testing workflows?
  050_executed_command: feature-testing-workflow --help-workflows
  060_command_prefix: docker exec -it --user neurospaces workflow_install_testing_opensuse_container bash -ic
report_error_directory: ./report_workflow-automation-engine/017-find-correct-commands-feature-testing-workflows
summary_filename: ./report_workflow-automation-engine/017-find-correct-commands-feature-testing-workflows/000_summary.yml